### ISSUE TITLE
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler

### ISSUE THREAD

**Issue by n30h4x0r** [exynos-linux-stable/crownlte#9]
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler

**Comment by cawilliamson** [comment]
I'm not related to the ELS project so others may have other opinions here but your error indicates that your compiler simply doesn't support stackprotector. With that in mind you have a couple of options really:

1.) Change Linux distribution (or run another distribution in a Docker container / VM if preferred - Ubuntu 18.04 is my preferred build distro of choice simply because it has a lot of support - 16.04 has even more support but is a bit dated at this point.)

2.) Simply edit the `arch/arm64/configs/exynos9810-crownlte_defconfig` file and change the following line:

`CONFIG_CC_STACKPROTECTOR_STRONG=y`

to:

`# CONFIG_CC_STACKPROTECTOR_STRONG is not set`

I would *not* recommend this approach since you are essentially changing the ELS codebase slightly and disabling a security feature but if that's your only option - it's better than not being able to build at all.

**Comment by farovitus** [comment]
Check your build script sir, you don't need to change or disable any option from defconfig to compile this source.
